package models;
// Generated 20/Mai/2013 14:00:49 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
public class Categoria  implements java.io.Serializable {


     private int id;
     private String nome;
     private String descricao;
     private BigDecimal precoDeposito;
     private BigDecimal precoPorHora;
     private Set<Carro> carros = new HashSet<Carro>(0);

    public Categoria() {
    }

	
    public Categoria(int id, String nome, String descricao, BigDecimal precoDeposito, BigDecimal precoPorHora) {
        this.id = id;
        this.nome = nome;
        this.descricao = descricao;
        this.precoDeposito = precoDeposito;
        this.precoPorHora = precoPorHora;
    }
    public Categoria(int id, String nome, String descricao, BigDecimal precoDeposito, BigDecimal precoPorHora, Set<Carro> carros) {
       this.id = id;
       this.nome = nome;
       this.descricao = descricao;
       this.precoDeposito = precoDeposito;
       this.precoPorHora = precoPorHora;
       this.carros = carros;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public BigDecimal getPrecoDeposito() {
        return this.precoDeposito;
    }
    
    public void setPrecoDeposito(BigDecimal precoDeposito) {
        this.precoDeposito = precoDeposito;
    }
    public BigDecimal getPrecoPorHora() {
        return this.precoPorHora;
    }
    
    public void setPrecoPorHora(BigDecimal precoPorHora) {
        this.precoPorHora = precoPorHora;
    }
    public Set<Carro> getCarros() {
        return this.carros;
    }
    
    public void setCarros(Set<Carro> carros) {
        this.carros = carros;
    }




}


