package models;
// Generated 20/Mai/2013 14:00:49 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Cidade generated by hbm2java
 */
public class Cidade  implements java.io.Serializable {


     private int id;
     private Pais pais;
     private String nome;
     private Set<Local> locals = new HashSet<Local>(0);

    public Cidade() {
    }

	
    public Cidade(int id, Pais pais, String nome) {
        this.id = id;
        this.pais = pais;
        this.nome = nome;
    }
    public Cidade(int id, Pais pais, String nome, Set<Local> locals) {
       this.id = id;
       this.pais = pais;
       this.nome = nome;
       this.locals = locals;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Pais getPais() {
        return this.pais;
    }
    
    public void setPais(Pais pais) {
        this.pais = pais;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set<Local> getLocals() {
        return this.locals;
    }
    
    public void setLocals(Set<Local> locals) {
        this.locals = locals;
    }




}


