package models;
// Generated 20/Mai/2013 14:00:49 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Local generated by hbm2java
 */
public class Local  implements java.io.Serializable {


     private int id;
     private Cidade cidade;
     private String nome;
     private BigDecimal latitude;
     private BigDecimal longitude;
     private Set<Servico> servicosForLocalPartidaid = new HashSet<Servico>(0);
     private Set<Servico> servicosForLocalChegadaid = new HashSet<Servico>(0);

    public Local() {
    }

	
    public Local(int id, Cidade cidade, String nome) {
        this.id = id;
        this.cidade = cidade;
        this.nome = nome;
    }
    public Local(int id, Cidade cidade, String nome, BigDecimal latitude, BigDecimal longitude, Set<Servico> servicosForLocalPartidaid, Set<Servico> servicosForLocalChegadaid) {
       this.id = id;
       this.cidade = cidade;
       this.nome = nome;
       this.latitude = latitude;
       this.longitude = longitude;
       this.servicosForLocalPartidaid = servicosForLocalPartidaid;
       this.servicosForLocalChegadaid = servicosForLocalChegadaid;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Cidade getCidade() {
        return this.cidade;
    }
    
    public void setCidade(Cidade cidade) {
        this.cidade = cidade;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public BigDecimal getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(BigDecimal latitude) {
        this.latitude = latitude;
    }
    public BigDecimal getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(BigDecimal longitude) {
        this.longitude = longitude;
    }
    public Set<Servico> getServicosForLocalPartidaid() {
        return this.servicosForLocalPartidaid;
    }
    
    public void setServicosForLocalPartidaid(Set<Servico> servicosForLocalPartidaid) {
        this.servicosForLocalPartidaid = servicosForLocalPartidaid;
    }
    public Set<Servico> getServicosForLocalChegadaid() {
        return this.servicosForLocalChegadaid;
    }
    
    public void setServicosForLocalChegadaid(Set<Servico> servicosForLocalChegadaid) {
        this.servicosForLocalChegadaid = servicosForLocalChegadaid;
    }




}


