package models;
// Generated 20/Mai/2013 14:00:49 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Pais generated by hbm2java
 */
public class Pais  implements java.io.Serializable {


     private int id;
     private String nome;
     private Set<Cidade> cidades = new HashSet<Cidade>(0);

    public Pais() {
    }

	
    public Pais(int id, String nome) {
        this.id = id;
        this.nome = nome;
    }
    public Pais(int id, String nome, Set<Cidade> cidades) {
       this.id = id;
       this.nome = nome;
       this.cidades = cidades;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set<Cidade> getCidades() {
        return this.cidades;
    }
    
    public void setCidades(Set<Cidade> cidades) {
        this.cidades = cidades;
    }




}


