package models;
// Generated 20/Mai/2013 14:00:49 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * Servico generated by hbm2java
 */
public class Servico  implements java.io.Serializable {


     private int id;
     private Utilizador utilizador;
     private Carro carro;
     private Local localByLocalChegadaid;
     private Local localByLocalPartidaid;
     private Date dataPartida;
     private Date dataChegada;
     private boolean depositoCheio;
     private BigDecimal preco;
     private Integer obs;

    public Servico() {
    }

	
    public Servico(int id, Utilizador utilizador, Carro carro, Local localByLocalChegadaid, Local localByLocalPartidaid, Date dataPartida, Date dataChegada, boolean depositoCheio, BigDecimal preco) {
        this.id = id;
        this.utilizador = utilizador;
        this.carro = carro;
        this.localByLocalChegadaid = localByLocalChegadaid;
        this.localByLocalPartidaid = localByLocalPartidaid;
        this.dataPartida = dataPartida;
        this.dataChegada = dataChegada;
        this.depositoCheio = depositoCheio;
        this.preco = preco;
    }
    public Servico(int id, Utilizador utilizador, Carro carro, Local localByLocalChegadaid, Local localByLocalPartidaid, Date dataPartida, Date dataChegada, boolean depositoCheio, BigDecimal preco, Integer obs) {
       this.id = id;
       this.utilizador = utilizador;
       this.carro = carro;
       this.localByLocalChegadaid = localByLocalChegadaid;
       this.localByLocalPartidaid = localByLocalPartidaid;
       this.dataPartida = dataPartida;
       this.dataChegada = dataChegada;
       this.depositoCheio = depositoCheio;
       this.preco = preco;
       this.obs = obs;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Utilizador getUtilizador() {
        return this.utilizador;
    }
    
    public void setUtilizador(Utilizador utilizador) {
        this.utilizador = utilizador;
    }
    public Carro getCarro() {
        return this.carro;
    }
    
    public void setCarro(Carro carro) {
        this.carro = carro;
    }
    public Local getLocalByLocalChegadaid() {
        return this.localByLocalChegadaid;
    }
    
    public void setLocalByLocalChegadaid(Local localByLocalChegadaid) {
        this.localByLocalChegadaid = localByLocalChegadaid;
    }
    public Local getLocalByLocalPartidaid() {
        return this.localByLocalPartidaid;
    }
    
    public void setLocalByLocalPartidaid(Local localByLocalPartidaid) {
        this.localByLocalPartidaid = localByLocalPartidaid;
    }
    public Date getDataPartida() {
        return this.dataPartida;
    }
    
    public void setDataPartida(Date dataPartida) {
        this.dataPartida = dataPartida;
    }
    public Date getDataChegada() {
        return this.dataChegada;
    }
    
    public void setDataChegada(Date dataChegada) {
        this.dataChegada = dataChegada;
    }
    public boolean isDepositoCheio() {
        return this.depositoCheio;
    }
    
    public void setDepositoCheio(boolean depositoCheio) {
        this.depositoCheio = depositoCheio;
    }
    public BigDecimal getPreco() {
        return this.preco;
    }
    
    public void setPreco(BigDecimal preco) {
        this.preco = preco;
    }
    public Integer getObs() {
        return this.obs;
    }
    
    public void setObs(Integer obs) {
        this.obs = obs;
    }




}


