INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7502,'Estação Ermesinde','558');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7503,'Forum Ermesinde','559');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7504,'Igreja Ermesinde','560');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7505,'MaiaShopping','223');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7506,'MaiaShopping','224');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7507,'Rodrigues Freitas','561');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7508,'Rio Leça','562');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7509,'Travagem','563');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7510,'TV Simões Lopes','218');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7511,'Sampaio','219');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7512,'Central Sampaio','220');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7513,'Pedro Hispano','221');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7514,'Ardegães','226');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7515,'Prof. Augusto Rezende','227');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7516,'Centro Inspecções','228');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7517,'Pinhal','0');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7518,'Primavera (Nogueira)','230');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7519,'Monte Penedo','231');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7520,'Rio','232');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7521,'António Moreira da Silva','233');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7522,'TV Dr. Augusto Martins','234');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7523,'Jorge Ferreirinha','235');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7524,'Agostinho Silva Rocha','236');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7525,'Cavaco','237');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7526,'Souto','238');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7527,'D. Manuel II','239');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7528,'Altos','240');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7529,'Estádio Maia','241');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7530,'Sobreiro','242');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7531,'Maia','837');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7532,'Maia - Câmara Municipal','477');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7533,'Sobreiro','283');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7534,'Estádio Maia','284');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7535,'Altos','285');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7536,'D. Manuel II','286');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7537,'Souto','287');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7538,'Agostinho SIlva Rocha','289');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7539,'JOrge Ferreirinha','290');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7540,'TV Dr. Augusto Martins','291');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7541,'António Moreira Silva','292');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7542,'Rio Saída','293');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7543,'Rio','294');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7544,'Monte Penedo','295');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7545,'Primavera Nogueira','296');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7546,'Pinhal','297');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7547,'TV Ardegães','298');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7548,'Prof. Augusto Rezende','299');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7549,'Ardegães','300');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7550,'Pedro Hispano','301');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7551,'Samapio','302');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7552,'TV Simões LOpes','303');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7553,'Travagem','554');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7554,'Rio Leça','555');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7555,'Rodrigues Freitas','556');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7556,'Igreja Ermesinde','557');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7557,'Maia Forum','833');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7558,'Ferreira da Cruz','834');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7559,'Altino Coelho','391');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7560,'Pinta','392');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7561,'Aquilino Ribeiro','393');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7562,'Hipermercado','394');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7563,'Velha de Mandim','395');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7801,'Maia - Câmara Municipal','477');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7802,'Sobreiro','283');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7803,'Estádio Maia','284');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7804,'Altos','285');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7805,'D. Manuel II','286');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7806,'Souto','287');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7807,'Cavaco','288');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7808,'Agostinho SIlva Rocha','289');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7809,'Jorge Ferreirinha','290');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7810,'TV Dr. Augusto Martins','291');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7811,'António Moreira Silva','292');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7812,'Rio Saída','293');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7813,'Rio','294');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7814,'Monte Penedo','295');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7815,'Primavera Nogueira','296');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7816,'Pinhal','297');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7817,'TV Ardegães','298');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7818,'Prof. Augusto Rezende','299');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7819,'Ardegães','300');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7820,'Via Ardegães','222');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7821,'MaiaShopping','224');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7822,'MaiaShopping','223');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7823,'Via Ardegães','0');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7824,'Central Ardegães','564');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7825,'Largo de Ardegães','565');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7826,'Fonte Novais','566');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7827,'Ponte de Ardegães','567');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7828,'Rebordãos','568');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7829,'Cruzeiro','569');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7830,'Central da Corga','570');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7831,'Centro Saúde','571');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7832,'Meilão','572');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7833,'Côrga','573');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7834,'Águas Santas','574');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7835,'R. do Mosteiro','575');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7836,'António Santos','576');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7837,'Formigueiro','577');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7838,'Guadalupe','578');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7839,'Dr. Carlos Felgueiras','582');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7840,'5 de Outubro','583');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7841,'D  Dinis','584');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7842,'Vencedores','585');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7843,'S. Gemil','586');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7844,'Paiol','587');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7845,'Dr. António Castro Meireles','588');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7846,'Cutamas','589');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7847,'António Simões','590');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7848,'Pedrouços de Baixo','591');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7849,'Junta Freguesia de Pedrouços','592');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7850,'Gonc. Mendes da Maia','593');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7851,'Areosa','594');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7852,'Areosa - Costa Cabral','601');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7853,'Alto Areosa','602');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7854,'António Coelho','603');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7855,'Santa Justa','604');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7856,'Centro Saude','605');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7857,'Conde Ferreira','606');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7858,'Luis Woodhouse','607');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7859,'Silva Tapada','608');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7860,'Pires de Lima','609');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7861,'Combatentes','610');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7862,'Perpetuo Socorro','611');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7863,'Marquês','612');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7864,'Doze Casas','613');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7865,'Fontinha','614');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7866,'Jornal Noticias','615');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7867,'Praça da República','616');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7868,'Praça da República','616');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7869,'Jornal de Noticias','617');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7870,'Fontinha','618');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7871,'Doze Casas','619');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7872,'Marquês','620');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7873,'Perpetuo Socorro','621');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7874,'Combatentes','622');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7875,'Pires de Lima','623');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7876,'Silva Tapada','624');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7877,'Luis Woodhouse','625');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7878,'Conde FerreIra','626');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7879,'Centro de Saude','627');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7880,'Santa Justa','628');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7881,'António Coelho','629');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7882,'Alto da Areosa','630');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7883,'Areosa - Costa Cabral','631');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7884,'Areosa','633');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7885,'Enxurreiras','634');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7886,'Junta de Freguesia','635');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7887,'Pedrouços - Bombeiros','636');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7888,'Pedrouços - Cemitério','637');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7889,'Cutamas','638');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7890,'António Castro Meireles','639');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7891,'Paiol','640');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7892,'S. Gemil','6410');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7893,'Vencedores','642');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7894,'D. Dinis','643');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7895,'5 de Outubro','644');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7896,'Dr. Carlos Felgueiras','645');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7897,'Guadalupe','579');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7898,'Formigueiro','580');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7899,'António Santos','581');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7900,'R. do Mosteiro','646');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7901,'Águas Santas','647');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7902,'Corga','648');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7903,'Calvário','649');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7904,'Meilão','650');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7993,'Centro Saude','651');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7994,'Central da Corga','652');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7995,'Cruzeiro','653');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7996,'Rebordãos','654');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7997,'Ardegães Ponte','655');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7998,'Fonte de Novais','656');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(7999,'Largo de Ardegães','657');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8000,'Central Ardegães','658');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8109,'Vilar de Luz','1');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8110,'Borralhas','2');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8111,'Camposa','3');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8112,'Horizonte','4');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8113,'Tv Horizonte','5');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8114,'Tv Fonte Leite','6');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8115,'Estação (S. Romão)','7');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8116,'Seixal','8');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8117,'Cegonheira','9');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8118,'Mamoa','10');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8119,'Igreja (S. Romão)','11');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8120,'Pereiró','12');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8121,'Biqueira','13');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8122,'Casal','14');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8123,'Monte Soeiro','15');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8124,'Nossa Senhora Lurdes','16');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8125,'Igreja S. Mamede Coronado','17');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8126,'Covelo','18');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8127,'Parque de Jogos','19');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8128,'Feira Nova','20');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8129,'Ensino','21');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8130,'Monte','22');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8131,'Trinaterra','23');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8132,'Terra Cavada','24');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8133,'Cavadinha','25');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8134,'Sá','26');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8135,'Junta Freguesia Silva Escura','27');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8136,'Taim','28');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8137,'Alvaro Moutinho das Neves','29');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8138,'Devesa','30');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8139,'Carvalho','31');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8140,'Igreja Nogueira','32');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8141,'General Carmona','33');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8142,'Estádio Municipal','34');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8143,'União Nogueirense','35');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8144,'Dr. Augusto Martins','36');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8145,'Barroso','37');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8146,'Rio','38');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8147,'Sidónio Pais','39');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8148,'Codiçais','40');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8149,'Conchas','41');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8150,'Arroteia','42');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8151,'Vessada','43');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8152,'Milheiros','44');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8153,'Agra','45');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8154,'1º Maio','46');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8155,'Rod. Gonçalves Lage Oeste','47');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8156,'Terramonte','48');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8157,'Parada','49');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8158,'Leonardo Coimbra','50');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8159,'Henrique Bravo','51');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8160,'Laranjeiras','52');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8161,'Igreja (S. M. Infesta)','53');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8162,'S. Mamede','54');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8163,'Mercado','55');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8164,'Flores','56');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8165,'Telheiro','57');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8166,'Amial','58');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8167,'Azenha - Amial','59');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8168,'Berlengas','60');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8169,'Telheira','61');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8170,'Carlos Amarante','62');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8171,'Cintura Interna','63');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8172,'Arca D`Água','64');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8173,'Centro Sausde','65');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8174,'Vale Formoso','66');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8175,'Constituição','67');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8176,'Hospital Sta. Maria','68');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8177,'Lapa','69');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8178,'Praça da República','70');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8179,'Trindade','71');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8180,'Aliados','73');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8181,'Guilherme Gomes Fernandes','74');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8182,'Carmo','75');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8183,'Corodaria','76');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8184,'Aliados','77');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8185,'Trindade - Metro','79');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8186,'João das Regras','80');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8187,'Lapa','81');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8188,'Hospital Santa Maria','82');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8189,'Constituição','83');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8190,'Vale Formoso','84');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8191,'Centro Saude','85');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8192,'Arca D`Água','86');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8193,'Cintura Interna','87');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8194,'Carlos Amarante','88');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8195,'Telheira','89');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8196,'Berlengas','90');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8197,'Azenha - Amial','91');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8198,'Telheiro','92');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8199,'Flores','93');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8200,'Mercado','94');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8201,'S. Mamede','95');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8202,'Igreja (S. Mamede Infesta)','96');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8203,'Laranjeiras','97');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8204,'Henriqe Bravo','98');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8205,'Leonardo Coimbra','99');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8206,'Parada','100');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8207,'Terramonte','101');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8208,'Gonçalves Lage Oeste','102');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8209,'1º Maio','103');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8210,'Agra','104');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8211,'Milheirós','105');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8212,'Vessada','106');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8213,'Arroteia','107');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8214,'Conchas','1080');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8215,'Codiçais','109');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8216,'Sidóno Pais','110');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8217,'Rio','111');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8218,'Barroso','112');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8219,'Igreja Nogueira','113');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8220,'Carvalho','114');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8221,'Devesa','115');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8222,'Alvaro Moutinho das Neves','116');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8223,'Taim','117');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8224,'Junta Freguesia Silva Escura','118');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8225,'Sá','119');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8226,'Cavadinha','120');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8227,'Terra Cavada','121');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8228,'Trinaterra','122');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8229,'Monte','123');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8230,'Ensino','124');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8231,'Feira Nova','125');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8232,'Parque de Jogos','126');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8233,'Covelo','127');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8234,'Igreja S. Mamede Coronado','128');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8235,'Nossa Senhora Lurdes','129');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8236,'Monte Soeiro','0');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8237,'Casal','131');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8238,'Biqueira','133');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8239,'Pereiró','133');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8240,'Igreja S. Romão','134');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8241,'Mamoa','135');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8242,'Cegonheira','136');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8243,'Seixal','137');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8244,'Estação S. Romão','138');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8245,'TV Fonte Leite','139');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8246,'Tv Horizonte','140');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8247,'Horixonte','141');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8248,'Camposa','142');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8249,'TV Sidónio Pais','659');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8250,'Agra (Milheirós)','660');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8251,'Matadouro','661');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8252,'Flores','662');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8253,'Igreja Gueifães','663');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8254,'Padre Américo','664');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8255,'Manuel Ferreira Pinto','665');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8256,'Penedos','666');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8257,'Mogos','667');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8258,'Francisco Coelho','668');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8259,'Maninhos','669');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8260,'Fernando Pessoa','670');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8261,'Santo António','671');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8262,'Lavrador','672');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8263,'Santos Leite','673');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8264,'Igreja Maia','674');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8265,'Bairro Siderurgia','884');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8266,'José Régio','527');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8267,'Raposeira','527');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8268,'Junta de Freguesia Barca','528');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8269,'Gestalinho','533');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8270,'Alambique','534');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8271,'Bela Vista','0');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8272,'Aurélio Silva','886');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8273,'E B 2/3 Castelo','381');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8274,'Centro Saude','538');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8275,'Secundária Castelo','380');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8276,'E B 2/3 CAstelo da Maia','381');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8277,'Agra (Castelo)','887');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8278,'Bela Vista','520');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8279,'Alambique','521');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8280,'Getsalinho','522');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8281,'Junta Freguesia Barca','529');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8282,'Raposeira','841');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8283,'José Régio','840');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8284,'Bairro Siderurgia','885');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8285,'Pinta','386');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8286,'Altino Coelho','387');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8287,'Ferreira da Cruz','835');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8288,'Forum Maia','836');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8289,'Maia - Câmara Municipal','282');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8290,'Luis de Camões','888');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8291,'Lage','842');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8292,'Vasco da Gama','843');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8293,'Tv Augusto Simões','844');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8294,'Santo António','677');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8295,'Fernando Pessoa','678');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8296,'Maninhos','679');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8297,'Francisco Coelho','680');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8298,'Mogos','681');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8299,'Penedos','682');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8300,'Manuel Ferreira Pinto','683');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8301,'Padre Américo','684');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8302,'Igreja Gueifães','685');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8303,'Flores','686');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8304,'Matadouro','687');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8305,'Agra (Milheiros)','688');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8306,'Fonte Leite','143');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8307,'Carvoeiras','144');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8308,'Outeiral','145');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8309,'Carreira','146');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8310,'Castanhal','147');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8311,'Vale Igreja','148');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8312,'R. de Cima','149');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8313,'Central','150');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8314,'S. Gonçalo','151');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8315,'Pedaços','152');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8316,'Av 1º de Maio','153');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8317,'Cruz','154');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8318,'Bela Vista','155');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8319,'Souto','156');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8320,'Lemende','157');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8321,'Pero Pinheiro','158');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8322,'Tv Liberdade','159');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8323,'Colmeias','160');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8324,'Mosteiro Beneditino','161');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8325,'Santa Barbara','162');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8326,'Vitorino','163');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8327,'Dr. Lima Carneiro','164');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8328,'Vitorino','165');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8329,'Santa Barbara','166');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8330,'Mosteiro Beneditino','167');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8331,'Colmeias','168');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8332,'Tv Liberdade','169');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8333,'Pero Pinheiro','170');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8334,'Lemende','171');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8335,'Souto','172');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8336,'Bela Vista','173');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8337,'Cruz','174');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8338,'1º de Maio','175');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8339,'Pedaços','176');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8340,'S. Gonçalo','177');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8341,'Central','178');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8342,'R  de Cima','179');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8343,'Vale Igreja','180');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8344,'Castanhal','181');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8345,'Carreira','182');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8346,'Outeiral','183');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8347,'Carvoeiras','184');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8348,'Fonte Leite','185');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8349,'Dr. Délio Santarém','186');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8350,'São Bartolomeu','187');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8351,'Progitela','188');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8352,'Largo Seixinho','189');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8353,'Humberto Delgado','190');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8354,'Seixinho','191');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8355,'Seixinho','192');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8356,'Humberto Delgado','193');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8357,'Largo Seicinho','194');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8358,'Profitela','195');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8359,'São Bartolomeu','196');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8360,'Dr. Délio Santarém','197');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8361,'Fonte Cova','396');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8362,'Campo de Futebol','397');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8363,'Estação Castelo da Maia','539');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8364,'Quinta Amarela','540');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8365,'5 de Outubro','541');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8366,'Mercado Castêlo','698');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8367,'Ismai','699');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8368,'Bairro','707');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8369,'Cruzeiro Ante','845');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8370,'Estação S. Romão','198');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8371,'Agua Levada','488');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8372,'Jorge de Sena','489');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8373,'Portela','490');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8374,'Cidadelha','491');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8375,'Tv. Ponte','492');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8376,'Monte','493');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8377,'Central Cidadelha','494');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8378,'Pisco','495');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8379,'S. José','496');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8380,'Mário Clemente','504');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8381,'Senhora da Agonia','505');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8382,'Santo António','506');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8383,'Augusto Nogueira da Silva','513');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8384,'Mercado','514');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8385,'5 de Outubro','515');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8386,'Quinta Amarela','0');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8387,'Estação Castêlo da Maia','517');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8388,'Centro Saude','518');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8389,'E. B . 2/3 Castelo Maia','398');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8390,'Escola Secundária Castelo da Maia','399');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8391,'Aurélio Silva Maia','519');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8392,'Junta Freguesia de Barca','523');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8393,'Padre Abilio Sampaio','524');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8394,'Hipermercado','525');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8395,'Aquilino Ribeiro','385');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8396,'Padre Abilio Sampaio','530');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8397,'Junta Freguesia de Barca','531');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8398,'EB 1 Gestalinho','532');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8399,'Secundária Castelo da Maia','537');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8400,'Estação Castelo da Maia','539');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8401,'Quinta Amarela','540');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8402,'Mercado (Castêlo)','500');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8403,'Augusto Nogueira da Silva','501');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8404,'Santo António','502');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8405,'Senhora da Agonia','503');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8406,'Mário Clemente','504');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8407,'Largo S  José ','545');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8408,'Central Cidadelha','546');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8409,'Pisco','547');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8410,'Monte','548');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8411,'Tv. da Fonte','549');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8412,'Cidadelha','550');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8413,'Portela','551');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8414,'Jorge Sena','552');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8415,'Água Levada','553');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8416,'Ciccopn','507');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8417,'Agra Morta','508');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8418,'Agra Club','689');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8419,'Patriomónio','690');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8420,'Paiço','691');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8421,'Igreja S. Pedro Avioso','702');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8422,'Ferronho','703');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8423,'Paiço','704');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8424,'Património','705');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8425,'Agra Club','706');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8426,'Agra Morta','511');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8428,'Ciccopn','512');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8429,'Campo Futebol','382');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8430,'Velha Mandim','383');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8431,'Hipermercado','384');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8432,'Ribeiro','846');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8433,'Nova da Bajouca','847');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8434,'Rua E','848');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8435,'Caminho de Baixo','849');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8436,'Bairro Bajouca','850');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8437,'E. B. 1 Bajouca','851');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8438,'Cimo Vila','852');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8439,'Australias','853');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8440,'Sá','854');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8441,'Eucalipto Grosso','855');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8442,'Monte Abraes','856');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8443,'Junta Freguesia Gemunde','857');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8444,'Gemunde Farm','858');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8445,'Igreja Gemunde','859');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8446,'Souto','860');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8447,'Barranha','861');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8448,'Tv Outeiro','862');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8449,'Castanhal','863');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8450,'Outeiro','864');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8451,'Campos Verdes','442');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8452,'Frederico Ulrich','893');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8453,'Mestre Clara','443');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8454,'Guardeiras','444');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8455,'Cruz das Guardeiras','445');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8456,'LIdador','255');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8457,'Estação Pedras Rubras','256');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8458,'Dr. A. Carlos Maia','257');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8459,'Feira Pedras Rubras','258');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8460,'Feira Pedras Rubras','265');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8461,'Dr. A. Carlos Maia','266');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8462,'Estação Pedras Rubras','268');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8463,'Fernando Pessoa','455');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8464,'Cruz das Guardeiras','457');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8465,'Guardeiras','458');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8466,'Mestre Clara','459');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8467,'Frederico Ulrich','892');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8468,'Campos Verdes','460');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8469,'Outeiro','865');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8470,'Castanhal','866');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8471,'Tv Outeiro','867');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8472,'Barranha','868');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8473,'Souto','869');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8474,'Igreja Gemunde','870');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8475,'Gemunde Farm','891');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8476,'Junta Freguesia Gemunde','871');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8477,'Monte Abraes','872');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8478,'Eucalipto Grosso','873');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8479,'Sá','874');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8480,'Sá','874');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8482,'Cimo Vila','876');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8483,'E.B. 1 Bajouca','877');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8484,'Bairro Bajouca','878');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8485,'Caminho de Baixo','879');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8486,'Rua E','880');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8487,'Nova da Bajouca','881');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8488,'Ribeiro','882');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8489,'Cruzeiro Anta','883');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8490,'Bairro','718');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8491,'Ismai','696');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8492,'Mercado Castelo','697');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8493,'Escola Secundária Castêlo Maia','399');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8494,'Junta Freguesia Gondim','400');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8495,'Campo Futebol Gondim','401');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8496,'Igreja Gondim','402');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8497,'Alzira J. Guimarães','403');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8498,'Via Diagonal','889');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8499,'Arquinho','404');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8500,'Porto Bom','405');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8501,'Liberdade','406');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8502,'Nova de Frejufe','407');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8503,'Largo Frejufe','408');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8504,'Cantral Frejufe','409');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8505,'Nossa Senhora Caridade','410');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8506,'Cesário Verde','411');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8507,'Xisto','412');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8508,'Nogueirense','839');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8509,'Alexandre Herculano','413');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8510,'António Ferreira da Silva','414');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8511,'Viaduto','415');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8512,'Cardosas','416');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8513,'Apeadeiro','417');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8514,'S. Frutuoso','418');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8515,'Igreja Folgosa','324');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8516,'Agra','207');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8517,'Alto de Arcos','325');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8518,'Tv Eng Luis Almeida','326');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8519,'Calçada de Real','327');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8520,'Santa Cristina','328');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8521,'Av. 24 de Julho','329');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8522,'Serra','330');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8523,'Malmarinhas','331');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8524,'Baguim','332');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8525,'Dr. Francisco Sá Carneiro','333');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8526,'Correios Alfena','334');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8527,'Central Barreiro','335');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8528,'Senhora da Piedade','336');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8529,'E. B. 2/3 Alfena','337');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8530,'Varzea','338');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8531,'Junta Freguesia Alfena','339');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8532,'Igreja Alfena','340');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8533,'Cemitério Alfena','341');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8534,'Secundária Lombelho','342');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8535,'Comendador Matos','343');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8536,'Igreja Alfena','344');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8537,'Junta Freguesia Alfena','345');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8538,'Varzea','346');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8539,'E. B. 2/3 Alfena','347');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8540,'Senhora Piedade','348');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8541,'Central do Barreiro','349');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8542,'Correios Alfena','350');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8543,'Dr. Francisco Sá Carneiro','351');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8544,'Baguim','352');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8545,'Malmarinhas','353');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8546,'Av. 24 Julho','354');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8547,'Santa Cristina','355');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8548,'Calçada Real','356');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8549,'Tv. Eng. Luis Almeida','357');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8550,'ALto de Arcos','358');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8551,'Agra','314');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8552,'Igreja Folgosa','359');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8553,'S. Frutuoso','360');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8554,'Apeadeiro','361');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8555,'Cardosas','362');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8556,'Viaduto','363');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8557,'António Ferreira da Silva','364');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8558,'Alexandre Herculano','365');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8559,'Nogueirense','838');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8560,'Xisto','367');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8561,'Cesário Verde','368');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8562,'Nossa Senhora Caridade','369');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8563,'Central de Frejufe','370');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8564,'Largo Frejufe','484');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8565,'Nova de Frejufe','372');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8566,'Liberdade','373');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8567,'Porto Bom','374');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8568,'Arquinho','375');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8569,'Via Diagonal','890');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8570,'Alzira J. Magalhães','376');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8571,'Igreja Gondim','377');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8572,'Campo Futebol Gondim','378');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8573,'Junta Freguesia de Gondim','379');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8574,'Xisto','421');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8575,'Varzea','422');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8576,'Soutinho','423');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8577,'Igreja Vermoim','424');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8578,'Padre Manuel Alves Rego','425');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8579,'Nova dos Altos','426');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8580,'Nova dos Altos','478');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8581,'Padre Manuel Alves Rego','479');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8582,'Igreja Vermoim','480');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8583,'Soutinho','481');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8584,'Varzea','482');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8585,'Xisto','483');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8586,'Bairro Folgosa','322');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8587,'Piscinas Folgosa','323');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8588,'Calvário','204');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8589,'Senra','205');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8590,'Igreja Folgosa','206');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8591,'Igreja Silva Escura','419');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8592,'Largo Frejufe','420');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8593,'Largo Frejufe','484');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8594,'Igreja Silva Escura','485');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8595,'Igreja Folgosa','315');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8596,'Senra','316');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8597,'Calvário','317');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8598,'Piscinas Folgosa','487');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8599,'Bairro Folgosa','486');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8600,'E. B: 2/3 Nogueira','827');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8601,'Escolas Maia','829');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8602,'Luis de Camões','830');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8603,'S. P. Fins (C. Futebol)','798');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8604,'Central','208');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8606,'Largo Curtiêlo','799');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8607,'Alberto Marques Gondão','800');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8608,'Penas','801');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8609,'Particular Amadeu Vilar','802');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8610,'Travagem Escolas','217');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8611,'E. B 2/3 Nogueira','828');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8613,'Travagem Escolas','304');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8614,'Particular Amadeu Vialar','803');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8615,'Penas','804');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8616,'Gondão','805');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8617,'Largo Curtiêlo','806');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8618,'Central','313');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8619,'Largo Ardegães','807');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8620,'Pisão','808');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8621,'Arregadas - Viaduto','809');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8622,'Quelhas','810');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8623,'Arregadas','811');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8624,'Igreja Milheirós','812');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8625,'Correios Milheirós','813');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8626,'Enxinhães','823');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8628,'Largo dos Mogos','824');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8629,'Casal dos Mogos','825');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8630,'Cavaco','826');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8641,'Aldeia Nova','818');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8642,'Conchas','819');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8643,'Centro Saude','820');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8644,'Tv Escolas','821');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8645,'Correios Milheirós','822');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8646,'Tv Escolas','814');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8647,'Centro Saude','816');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8648,'Conchas','0');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8649,'Aldeia Nova','817');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8650,'Centro Escolar Gandra','894');
INSERT INTO `eurotripsfinder`.`localparagem`(`id`,`nome`,`codigo`)VALUES(8651,'Centro Escolar Gandra','894');
