INSERT INTO `eurotripsfinder`.`rota`(`id`,`Companhiaid`,`nomecurto`,`nomelongo`,`tiporota`)VALUES(2820,187,'13','Ermesinde (Estação CP) - Maia (centro)',3);
INSERT INTO `eurotripsfinder`.`rota`(`id`,`Companhiaid`,`nomecurto`,`nomelongo`,`tiporota`)VALUES(2834,187,'30','Porto - Vilar de Luz',3);
INSERT INTO `eurotripsfinder`.`rota`(`id`,`Companhiaid`,`nomecurto`,`nomelongo`,`tiporota`)VALUES(2835,187,'11','Castêlo da Maia (Escolas) - Ermesinde (Estação C.P.)',3);
INSERT INTO `eurotripsfinder`.`rota`(`id`,`Companhiaid`,`nomecurto`,`nomelongo`,`tiporota`)VALUES(2836,187,'15','Trinaterra - Trofa',3);
INSERT INTO `eurotripsfinder`.`rota`(`id`,`Companhiaid`,`nomecurto`,`nomelongo`,`tiporota`)VALUES(2837,187,'18','Maia - Seixinho',3);
INSERT INTO `eurotripsfinder`.`rota`(`id`,`Companhiaid`,`nomecurto`,`nomelongo`,`tiporota`)VALUES(2838,187,'20','Maia - Pedras Rubras (Feira)',3);
INSERT INTO `eurotripsfinder`.`rota`(`id`,`Companhiaid`,`nomecurto`,`nomelongo`,`tiporota`)VALUES(2839,187,'28','Maia - S. Romão (Estação C.P.)',3);
INSERT INTO `eurotripsfinder`.`rota`(`id`,`Companhiaid`,`nomecurto`,`nomelongo`,`tiporota`)VALUES(2840,187,'12','Avioso (S. Pedro) - Ermesinde (Estação C.P.)',3);
INSERT INTO `eurotripsfinder`.`rota`(`id`,`Companhiaid`,`nomecurto`,`nomelongo`,`tiporota`)VALUES(2841,187,'12','Avioso (S. Pedro) - Ermesinde (Estação C.P.)',3);
INSERT INTO `eurotripsfinder`.`rota`(`id`,`Companhiaid`,`nomecurto`,`nomelongo`,`tiporota`)VALUES(2850,187,'30','Porto - Vilar de Luz',3);
INSERT INTO `eurotripsfinder`.`rota`(`id`,`Companhiaid`,`nomecurto`,`nomelongo`,`tiporota`)VALUES(2853,187,'25','Alfena (Esc. Sec. Lombelho) - Maia (Praça do Municipio)',3);
INSERT INTO `eurotripsfinder`.`rota`(`id`,`Companhiaid`,`nomecurto`,`nomelongo`,`tiporota`)VALUES(2854,187,'26','Gondim - Maia',3);
INSERT INTO `eurotripsfinder`.`rota`(`id`,`Companhiaid`,`nomecurto`,`nomelongo`,`tiporota`)VALUES(2855,187,'50','Maia - Vilar de Luz',3);
INSERT INTO `eurotripsfinder`.`rota`(`id`,`Companhiaid`,`nomecurto`,`nomelongo`,`tiporota`)VALUES(2856,187,'43','Escola Secundária da Maia - Vilar Luz',3);
INSERT INTO `eurotripsfinder`.`rota`(`id`,`Companhiaid`,`nomecurto`,`nomelongo`,`tiporota`)VALUES(2857,187,'42','Castêlo da Maia (Escolas) - S. P. Fins (C. Futebol)',3);
INSERT INTO `eurotripsfinder`.`rota`(`id`,`Companhiaid`,`nomecurto`,`nomelongo`,`tiporota`)VALUES(2858,187,'42','Castêlo da Maia (Escolas) - S. P. Fins (C. Futebol)',3);
INSERT INTO `eurotripsfinder`.`rota`(`id`,`Companhiaid`,`nomecurto`,`nomelongo`,`tiporota`)VALUES(2871,187,'41','E. B. 2/3 Nogueira - Xisto',3);
INSERT INTO `eurotripsfinder`.`rota`(`id`,`Companhiaid`,`nomecurto`,`nomelongo`,`tiporota`)VALUES(2873,187,'41','E. B. 2/3 Nogueira - Xisto',3);
INSERT INTO `eurotripsfinder`.`rota`(`id`,`Companhiaid`,`nomecurto`,`nomelongo`,`tiporota`)VALUES(2877,187,'41','E. B. 2/3 Nogueira - Xisto',3);
INSERT INTO `eurotripsfinder`.`rota`(`id`,`Companhiaid`,`nomecurto`,`nomelongo`,`tiporota`)VALUES(2879,187,'41','E. B. 2/3 Nogueira - Xisto',3);
INSERT INTO `eurotripsfinder`.`rota`(`id`,`Companhiaid`,`nomecurto`,`nomelongo`,`tiporota`)VALUES(2881,187,'10','Maia - Porto (Praça da República por Ardegães e Maiashopping)',3);
INSERT INTO `eurotripsfinder`.`rota`(`id`,`Companhiaid`,`nomecurto`,`nomelongo`,`tiporota`)VALUES(2883,187,'10','Maia - Porto (Praça da Rpública por Ardegães e Maiashopping)',3);
INSERT INTO `eurotripsfinder`.`rota`(`id`,`Companhiaid`,`nomecurto`,`nomelongo`,`tiporota`)VALUES(2885,187,'10','Maia - Porto (Praça da República por Ardegães e Maiashopping)',3);
INSERT INTO `eurotripsfinder`.`rota`(`id`,`Companhiaid`,`nomecurto`,`nomelongo`,`tiporota`)VALUES(2887,187,'10','Maia - Porto (Praça da República por Ardegães e Maiashopping)',3);
INSERT INTO `eurotripsfinder`.`rota`(`id`,`Companhiaid`,`nomecurto`,`nomelongo`,`tiporota`)VALUES(2888,187,'11','Castêlo da Maia (Escolas) - Ermesinde (Estação C.P.)',3);
INSERT INTO `eurotripsfinder`.`rota`(`id`,`Companhiaid`,`nomecurto`,`nomelongo`,`tiporota`)VALUES(2890,187,'11','Castêlo da Maia (Escolas) - Ermesinde (Estação C.P.)',3);
INSERT INTO `eurotripsfinder`.`rota`(`id`,`Companhiaid`,`nomecurto`,`nomelongo`,`tiporota`)VALUES(2895,187,'25','Alfena (Esc. Sec. Lombelho) - Maia (Praça do Municipio)',3);
INSERT INTO `eurotripsfinder`.`rota`(`id`,`Companhiaid`,`nomecurto`,`nomelongo`,`tiporota`)VALUES(2896,187,'25','Alfena (Esc. Sec. Lombelho) - Maia (Praça do Municipio)',3);
INSERT INTO `eurotripsfinder`.`rota`(`id`,`Companhiaid`,`nomecurto`,`nomelongo`,`tiporota`)VALUES(2897,187,'25','Alfena (Esc. Sec. Lombelho) - Maia (Praça do Municipio)',3);
INSERT INTO `eurotripsfinder`.`rota`(`id`,`Companhiaid`,`nomecurto`,`nomelongo`,`tiporota`)VALUES(2898,187,'25','Alfena (Esc. Sec. Lombelho) - Maia (Praça do Municipio)',3);
INSERT INTO `eurotripsfinder`.`rota`(`id`,`Companhiaid`,`nomecurto`,`nomelongo`,`tiporota`)VALUES(2901,187,'50','Maia - Vilar de Luz',3);
INSERT INTO `eurotripsfinder`.`rota`(`id`,`Companhiaid`,`nomecurto`,`nomelongo`,`tiporota`)VALUES(2906,187,'10','Maia - Porto (Praça da República por Ardegães e Maiashopping)',3);
