ALTER TABLE Servico DROP FOREIGN KEY FKServico742812;
ALTER TABLE Servico DROP FOREIGN KEY FKServico68876;
ALTER TABLE Servico DROP FOREIGN KEY FKServico562328;
ALTER TABLE Servico DROP FOREIGN KEY FKServico196310;
ALTER TABLE Carro DROP FOREIGN KEY FKCarro67785;
ALTER TABLE Local DROP FOREIGN KEY FKLocal184904;
ALTER TABLE Cidade DROP FOREIGN KEY FKCidade869916;
ALTER TABLE ServicoTaxi DROP FOREIGN KEY FKServicoTax29215;
ALTER TABLE ServicoTaxi DROP FOREIGN KEY FKServicoTax311171;
ALTER TABLE ServicoTaxi DROP FOREIGN KEY FKServicoTax68191;
DROP TABLE IF EXISTS ServicoTaxi;
DROP TABLE IF EXISTS Utilizador;
DROP TABLE IF EXISTS Servico;
DROP TABLE IF EXISTS Categoria;
DROP TABLE IF EXISTS Carro;
DROP TABLE IF EXISTS Local;
DROP TABLE IF EXISTS Cidade;
DROP TABLE IF EXISTS Pais;

